id: uc_attribute_instance_widget_settings
label: Attribute field instance widget configuration
migration_tags:
  - Drupal 6
  - Drupal 7
  - Ubercart
  - Configuration
source:
  plugin: uc_attribute_value
  constants:
    entity_type: commerce_product_variation
    bundle: default
    field_name_prefix: attribute
    form_mode: default
    region: content
    settings: {}
    third_party_settings: {}
process:
  field_name:
    -
      plugin: migration_lookup
      migration: uc_attribute_field
      source: aid
    -
      plugin: extract
      index:
        - 1
    -
      plugin: skip_on_empty
      method: row
  entity_type: 'constants/entity_type'
  targetEntityType: 'constants/entity_type'
  bundle: 'constants/bundle'
  form_mode: 'constants/form_mode'
  'options/type':
    plugin: static_map
    source: display
    map:
      0: text
      1: options_select
      2: options_buttons
      3: boolean_checkbox
  'options/weight': weight
  'options/settings': 'constants/settings'
  'options/third_party_settings': 'constants/third_party_settings'
destination:
  plugin: component_entity_form_display
  destination_module: commerce_product
migration_dependencies:
  required:
    - uc_attribute_field_instance
