id: commerce1_cart_settings
label: Cart settings
migration_tags:
  - Drupal 7
  - Commerce
  - Configuration
source:
  plugin: variable
  variables:
    - commerce_cart_refresh_force
    - commerce_cart_refresh_frequency
    - commerce_cart_refresh_mode
  source_module: commerce_order
process:
  refresh_frequency:
    plugin: default_value
    source: commerce_cart_refresh_frequency
    default_value: 15
  refresh_mode:
    -
      plugin: commerce1_refresh_mode
      source:
        - commerce_cart_refressh_force
        - commerce_cart_refresh_mode
    -
      plugin: skip_on_empty
      method: process
destination:
  plugin: config
  config_name: commerce_order.commerce_order_type.default
